name: Node.js CI

on:
  workflow_dispatch:
  inputs:
    TARGET_REGISTRY:
      description: '仓库地址'
      required: true
      default: 'registry.cn-guangzhou.aliyuncs.com'
    TARGET_REPOSITORY:
      description: '空间名称'
      required: true
      default: 'kubesphere_wen'
  push:
    branches:
      - 'main'
      - 'demo'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'demo'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: zcunsoft/clklog-frontend
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # TODO: Use Secrets when Public
          username: min_rong716@163.com
          password: tackey008362
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            HTML_DIR=dist
      - name: Set Docker image tag
        id: set-tag
        run: echo "::set-output name=tag::$(if [ $GITHUB_REF == 'refs/heads/main' ]; then echo latest; else echo ${GITHUB_REF#refs/heads/}; fi)"
      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          # TODO: Use Secrets when Public
          registry: ${{ github.event.inputs.TARGET_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Aliyun Docker Registry
        run: |
          docker buildx imagetools create \
            --tag ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/clklog_frontend:${{ steps.set-tag.outputs.tag }} \
            q82618362/clklog-frontend:${{ steps.set-tag.outputs.tag }}
